TARGET = SolPix2018

CH554_SDCC= c:/Users/matt/Blinkinlabs-Repos/ch554_sdcc

FREQ_SYS = 187500

C_FILES = \
	main.c \
	$(CH554_SDCC)/include/debug.c

pre-flash:
	

include $(CH554_SDCC)/examples/Makefile.include
